### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by allthesignals** [vatbub/vatbubgitreports2#1]
Thank you for open sourcing this! I'd love to build a UI on top of it, but I'm not sure what the API endpoint expects. Does it accept post requests with JSON as the content body? Some examples would be awesome, and I'd be happy to contribute to the readme.

**Comment by vatbub** [comment]
Hey, I actually already built a GUI on top of it that you can use as an example. It is available [here](https://github.com/vatbub/common/blob/master/src/main/java/view/reporting/ReportingDialog.java). I hope this helps you. And of course feel free to post any issues you encounter 😀

**Comment by vatbub** [comment]
Hi, as it seems that you don't have any further problems, I am going to close this issue now. Feel free to open new ones in case you encounter anything :)
